---
  - name: Remove default route
    lineinfile: 
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=NO   
  - name: Add default route
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.1.1
  - name: Restart network
    service:
      name: network
      state: restarted
